Repository codestates-seb/seb45_main_023, pull requests merged in 2023-09, with the labels that each got.

#56 [Feat] #4 comment CRUD
  back/src/main/java/com/marbleUs/marbleUs/comment/controller/CommentController.java
  back/src/main/java/com/marbleUs/marbleUs/comment/dto/CommentPatchDto.java
  back/src/main/java/com/marbleUs/marbleUs/comment/dto/CommentPostDto.java
  back/src/main/java/com/marbleUs/marbleUs/comment/dto/CommentResponseDto.java
  back/src/main/java/com/marbleUs/marbleUs/comment/entity/Comment.java
  back/src/main/java/com/marbleUs/marbleUs/comment/mapper/CommentMapper.java
  back/src/main/java/com/marbleUs/marbleUs/comment/repository/CommentRepository.java
  back/src/main/java/com/marbleUs/marbleUs/comment/service/CommentService.java
  back/src/main/java/com/marbleUs/marbleUs/dummy/DummyDataLoader.java
  back/src/main/java/com/marbleUs/marbleUs/member/entity/Member.java
Labels: Bare Minimum, backend, feature

#76 Feat/fix blog image
  back/src/main/java/com/marbleUs/marbleUs/blog/controller/BlogController.java
  back/src/main/java/com/marbleUs/marbleUs/blog/dto/BlogResponseDto.java
  back/src/main/java/com/marbleUs/marbleUs/blog/entity/Blog.java
  back/src/main/java/com/marbleUs/marbleUs/blog/mapper/BlogMapper.java
  back/src/main/java/com/marbleUs/marbleUs/blog/service/BlogService.java
  back/src/main/java/com/marbleUs/marbleUs/common/tools/audit/Auditable.java
  back/src/main/java/com/marbleUs/marbleUs/common/tools/converter/MultipartJackson2HttpMessageConverter.java
  back/src/main/java/com/marbleUs/marbleUs/common/tools/counter/ViewCounter.java
  back/src/main/java/com/marbleUs/marbleUs/common/tools/entity/BaseEntity.java
  back/src/main/java/com/marbleUs/marbleUs/common/tools/enums/Stamps.java
  back/src/main/java/com/marbleUs/marbleUs/common/tools/enums/UserLocations.java
  back/src/main/java/com/marbleUs/marbleUs/common/tools/generator/MemberNickNameGenerator.java
  back/src/main/java/com/marbleUs/marbleUs/common/tools/generator/NickNameGenerator.java
  back/src/main/java/com/marbleUs/marbleUs/image/entity/Image.java
  back/src/main/java/com/marbleUs/marbleUs/image/service/ImageService.java
  back/src/main/java/com/marbleUs/marbleUs/member/controller/MemberController.java
  back/src/main/java/com/marbleUs/marbleUs/member/dto/MemberDto.java
  back/src/main/java/com/marbleUs/marbleUs/member/dto/MemberSummarizedResponse.java
  back/src/main/java/com/marbleUs/marbleUs/member/entity/Follow.java
  back/src/main/java/com/marbleUs/marbleUs/member/entity/Follower.java
  back/src/main/java/com/marbleUs/marbleUs/member/entity/Member.java
  back/src/main/java/com/marbleUs/marbleUs/member/mapper/MemberMapper.java
  back/src/main/java/com/marbleUs/marbleUs/member/repository/FollowRepository.java
  back/src/main/java/com/marbleUs/marbleUs/member/repository/FollowerRepository.java
  back/src/main/java/com/marbleUs/marbleUs/member/service/MemberService.java
Labels: Bare Minimum, backend

#77 Feat/fix base entity
  back/src/main/java/com/marbleUs/marbleUs/city/entity/City.java
  back/src/main/java/com/marbleUs/marbleUs/comment/entity/Comment.java
  back/src/main/java/com/marbleUs/marbleUs/comment/service/CommentService.java
  back/src/main/java/com/marbleUs/marbleUs/common/dummy/DummyDataLoader.java
  back/src/main/java/com/marbleUs/marbleUs/common/exception/ExceptionCode.java
  back/src/main/java/com/marbleUs/marbleUs/common/tools/MissionLevelUpVerifier.java
  back/src/main/java/com/marbleUs/marbleUs/common/tools/audit/Auditable.java
  back/src/main/java/com/marbleUs/marbleUs/common/tools/converter/MultipartJackson2HttpMessageConverter.java
  back/src/main/java/com/marbleUs/marbleUs/common/tools/counter/ViewCounter.java
  back/src/main/java/com/marbleUs/marbleUs/common/tools/entity/BaseEntity.java
  back/src/main/java/com/marbleUs/marbleUs/common/tools/enums/Stamps.java
  back/src/main/java/com/marbleUs/marbleUs/common/tools/enums/UserLocations.java
  back/src/main/java/com/marbleUs/marbleUs/common/tools/generator/MemberNickNameGenerator.java
  back/src/main/java/com/marbleUs/marbleUs/common/tools/generator/NickNameGenerator.java
Labels: Bare Minimum, backend

#78 [Feat] #58 weather
  back/build.gradle
  back/src/main/java/com/marbleUs/marbleUs/MarbleUsApplication.java
  back/src/main/java/com/marbleUs/marbleUs/city/dto/CityDto.java
  back/src/main/java/com/marbleUs/marbleUs/city/entity/City.java
  back/src/main/java/com/marbleUs/marbleUs/city/service/CityService.java
  back/src/main/java/com/marbleUs/marbleUs/common/dummy/DummyDataLoader.java
  back/src/main/java/com/marbleUs/marbleUs/common/exception/ExceptionCode.java
  back/src/main/java/com/marbleUs/marbleUs/image/entity/BlogImage.java
  back/src/main/java/com/marbleUs/marbleUs/image/entity/MemberImage.java
  back/src/main/java/com/marbleUs/marbleUs/weather/controller/WeatherApiScheduler.java
  back/src/main/java/com/marbleUs/marbleUs/weather/controller/WeatherController.java
  back/src/main/java/com/marbleUs/marbleUs/weather/dto/WeatherPatchDto.java
  back/src/main/java/com/marbleUs/marbleUs/weather/dto/WeatherPostDto.java
  back/src/main/java/com/marbleUs/marbleUs/weather/dto/WeatherResponseDto.java
  back/src/main/java/com/marbleUs/marbleUs/weather/entity/Weather.java
  back/src/main/java/com/marbleUs/marbleUs/weather/mapper/WeatherMapper.java
  back/src/main/java/com/marbleUs/marbleUs/weather/repository/WeatherRepository.java
  back/src/main/java/com/marbleUs/marbleUs/weather/service/WeatherService.java
  back/src/main/java/com/marbleUs/marbleUs/weather/weatherCoordiantes.csv
Labels: Bare Minimum, backend

#85 [Fix] #79 weather 저장 및 업데이트 처리 상황별 분리
  back/src/main/java/com/marbleUs/marbleUs/weather/controller/WeatherApiScheduler.java
  back/src/main/java/com/marbleUs/marbleUs/weather/service/WeatherApiService.java
Labels: Bare Minimum, backend, fix

#90 "feat/advance-MultiBlogSearch"
  back/src/main/java/com/marbleUs/marbleUs/multiSearch/controller/MultiSearchController.java
  back/src/main/java/com/marbleUs/marbleUs/multiSearch/service/SearchEngine.java
Labels: Advanced, backend

#92 [Fix] yml 파일, import문, 애너테이션, ExceptionCode 조금씩 수정
  back/src/main/java/com/marbleUs/marbleUs/common/exception/ExceptionCode.java
  back/src/main/java/com/marbleUs/marbleUs/mission/service/MissionService.java
  back/src/main/java/com/marbleUs/marbleUs/weather/service/WeatherApiService.java
  back/src/main/resources/application-local.yml
Labels: Bare Minimum, backend
